// Generated by gen_data.js from pokeplatinum/res/items/data/*.json.
// {[fork item id]: AI item record}. category: FULL_RESTORE | RECOVER_HP |
// RECOVER_STATUS | STAT_BOOSTER | GUARD_SPEC | POKEBALL | MAX.
// hp: -1 = full heal; cures: engine status/volatile ids; stages: engine boost keys.
'use strict';
module.exports = {
 "adamantorb": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 60,
  "hold": "dialgaboost"
 },
 "aguavberry": {
  "category": "MAX",
  "effectParam": 8,
  "flingPower": 10,
  "naturalGiftType": "dragon",
  "hold": "hprestorebitter"
 },
 "airmail": {
  "category": "MAX"
 },
 "amuletcoin": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 30,
  "hold": "moneyup"
 },
 "antidote": {
  "category": "RECOVER_STATUS",
  "cures": [
   "psn"
  ],
  "flingPower": 30
 },
 "apicotberry": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 10,
  "naturalGiftType": "ground",
  "hold": "pinchspdefup"
 },
 "armorfossil": {
  "category": "MAX",
  "flingPower": 100
 },
 "aspearberry": {
  "category": "RECOVER_STATUS",
  "cures": [
   "frz"
  ],
  "flingPower": 10,
  "naturalGiftType": "ice",
  "hold": "frzrestore"
 },
 "awakening": {
  "category": "RECOVER_STATUS",
  "cures": [
   "slp"
  ],
  "flingPower": 30
 },
 "azureflute": {
  "category": "MAX"
 },
 "babiriberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "steel",
  "hold": "weakensesteel"
 },
 "belueberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "electric"
 },
 "berryjuice": {
  "category": "RECOVER_HP",
  "hp": 20,
  "effectParam": 20,
  "flingPower": 30,
  "hold": "hprestore"
 },
 "bicycle": {
  "category": "MAX"
 },
 "bigmushroom": {
  "category": "MAX",
  "flingPower": 30
 },
 "bigpearl": {
  "category": "MAX",
  "flingPower": 30
 },
 "bigroot": {
  "category": "MAX",
  "effectParam": 30,
  "flingPower": 10,
  "hold": "leechboost"
 },
 "blackbelt": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 30,
  "hold": "strengthenfight"
 },
 "blackflute": {
  "category": "MAX",
  "effectParam": 50,
  "flingPower": 30
 },
 "blacksludge": {
  "category": "MAX",
  "effectParam": 16,
  "flingPower": 30,
  "hold": "hprestorepsntype"
 },
 "blackglasses": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 30,
  "hold": "strengthendark"
 },
 "bloommail": {
  "category": "MAX"
 },
 "blueflute": {
  "category": "RECOVER_STATUS",
  "cures": [
   "slp"
  ],
  "flingPower": 30
 },
 "bluescarf": {
  "category": "MAX",
  "flingPower": 10
 },
 "blueshard": {
  "category": "MAX",
  "flingPower": 30
 },
 "blukberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "fire"
 },
 "brickmail": {
  "category": "MAX"
 },
 "brightpowder": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 10,
  "hold": "accreduce"
 },
 "bubblemail": {
  "category": "MAX"
 },
 "burnheal": {
  "category": "RECOVER_STATUS",
  "cures": [
   "brn"
  ],
  "flingPower": 30
 },
 "calcium": {
  "category": "MAX",
  "flingPower": 30
 },
 "carbos": {
  "category": "MAX",
  "flingPower": 30
 },
 "charcoal": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 30,
  "hold": "strengthenfire"
 },
 "chartiberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "rock",
  "hold": "weakenserock"
 },
 "cheriberry": {
  "category": "RECOVER_STATUS",
  "cures": [
   "par"
  ],
  "flingPower": 10,
  "naturalGiftType": "fire",
  "hold": "przrestore"
 },
 "cherishball": {
  "category": "POKEBALL"
 },
 "chestoberry": {
  "category": "RECOVER_STATUS",
  "cures": [
   "slp"
  ],
  "flingPower": 10,
  "naturalGiftType": "water",
  "hold": "slprestore"
 },
 "chilanberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "normal",
  "hold": "weakennormal"
 },
 "choiceband": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "choiceatk"
 },
 "choicescarf": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "choicespeed"
 },
 "choicespecs": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "choicespatk"
 },
 "chopleberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "fighting",
  "hold": "weakensefight"
 },
 "clawfossil": {
  "category": "MAX",
  "flingPower": 100
 },
 "cleansetag": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "encountersdown"
 },
 "cobaberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "flying",
  "hold": "weakenseflying"
 },
 "coincase": {
  "category": "MAX"
 },
 "colburberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "dark",
  "hold": "weakensedark"
 },
 "contestpass": {
  "category": "MAX"
 },
 "cornnberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "bug"
 },
 "coupon1": {
  "category": "MAX"
 },
 "coupon2": {
  "category": "MAX"
 },
 "coupon3": {
  "category": "MAX"
 },
 "custapberry": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 10,
  "naturalGiftType": "ghost",
  "hold": "pinchpriority"
 },
 "dampmulch": {
  "category": "MAX",
  "flingPower": 30
 },
 "damprock": {
  "category": "MAX",
  "effectParam": 3,
  "flingPower": 60,
  "hold": "extendrain"
 },
 "dawnstone": {
  "category": "MAX",
  "flingPower": 80
 },
 "deepseascale": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "clamperlspdef"
 },
 "deepseatooth": {
  "category": "MAX",
  "flingPower": 90,
  "hold": "clamperlspatk"
 },
 "destinyknot": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "reciprocateinfat"
 },
 "direhit": {
  "category": "MAX",
  "flingPower": 30
 },
 "diveball": {
  "category": "POKEBALL"
 },
 "domefossil": {
  "category": "MAX",
  "flingPower": 100
 },
 "dracoplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusdragon",
  "holdType": "dragon"
 },
 "dragonfang": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 70,
  "hold": "strengthendragon"
 },
 "dragonscale": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 30,
  "hold": "evolveseadra"
 },
 "dreadplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusdark",
  "holdType": "dark"
 },
 "dubiousdisc": {
  "category": "MAX",
  "flingPower": 50,
  "hold": "evolveporygon2"
 },
 "durinberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "water"
 },
 "duskball": {
  "category": "POKEBALL"
 },
 "duskstone": {
  "category": "MAX",
  "flingPower": 80
 },
 "earthplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusground",
  "holdType": "ground"
 },
 "electirizer": {
  "category": "MAX",
  "flingPower": 80,
  "hold": "evolveelectabuzz"
 },
 "elixir": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 30
 },
 "energyroot": {
  "category": "RECOVER_HP",
  "hp": -56,
  "flingPower": 30
 },
 "energypowder": {
  "category": "RECOVER_HP",
  "hp": 50,
  "flingPower": 30
 },
 "enigmaberry": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 10,
  "naturalGiftType": "bug",
  "hold": "hprestorese"
 },
 "escaperope": {
  "category": "MAX",
  "flingPower": 30
 },
 "ether": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 30
 },
 "everstone": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "noevolve"
 },
 "expshare": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "expshare"
 },
 "expertbelt": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 10,
  "hold": "powerupse"
 },
 "explorerkit": {
  "category": "MAX"
 },
 "fashioncase": {
  "category": "MAX"
 },
 "figyberry": {
  "category": "MAX",
  "effectParam": 8,
  "flingPower": 10,
  "naturalGiftType": "bug",
  "hold": "hprestorespicy"
 },
 "firestone": {
  "category": "MAX",
  "flingPower": 30
 },
 "fistplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusfighting",
  "holdType": "fighting"
 },
 "flamemail": {
  "category": "MAX"
 },
 "flameorb": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "brnuser"
 },
 "flameplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusfire",
  "holdType": "fire"
 },
 "fluffytail": {
  "category": "MAX",
  "flingPower": 30
 },
 "focusband": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 10,
  "hold": "maybeendure"
 },
 "focussash": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "endure"
 },
 "freshwater": {
  "category": "RECOVER_HP",
  "hp": 50,
  "effectParam": 50,
  "flingPower": 30
 },
 "fullheal": {
  "category": "RECOVER_STATUS",
  "cures": [
   "slp",
   "psn",
   "brn",
   "frz",
   "par",
   "confusion"
  ],
  "flingPower": 30
 },
 "fullincense": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "prioritydown"
 },
 "fullrestore": {
  "category": "FULL_RESTORE",
  "hp": -1,
  "effectParam": 255,
  "cures": [
   "slp",
   "psn",
   "brn",
   "frz",
   "par",
   "confusion"
  ],
  "flingPower": 30
 },
 "galactickey": {
  "category": "MAX"
 },
 "ganlonberry": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 10,
  "naturalGiftType": "ice",
  "hold": "pinchdefup"
 },
 "goodrod": {
  "category": "MAX"
 },
 "gooeymulch": {
  "category": "MAX",
  "flingPower": 30
 },
 "gracidea": {
  "category": "MAX"
 },
 "grassmail": {
  "category": "MAX"
 },
 "greatball": {
  "category": "POKEBALL"
 },
 "greenscarf": {
  "category": "MAX",
  "flingPower": 10
 },
 "greenshard": {
  "category": "MAX",
  "flingPower": 30
 },
 "grepaberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "flying"
 },
 "gripclaw": {
  "category": "MAX",
  "flingPower": 90,
  "hold": "extendtrapping"
 },
 "griseousorb": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 60,
  "hold": "giratinaboost"
 },
 "growthmulch": {
  "category": "MAX",
  "flingPower": 30
 },
 "guardspec": {
  "category": "GUARD_SPEC",
  "guardSpec": true,
  "flingPower": 30
 },
 "habanberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "dragon",
  "hold": "weakensedragon"
 },
 "hardstone": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 100,
  "hold": "strengthenrock"
 },
 "healball": {
  "category": "POKEBALL"
 },
 "healpowder": {
  "category": "RECOVER_STATUS",
  "cures": [
   "slp",
   "psn",
   "brn",
   "frz",
   "par",
   "confusion"
  ],
  "flingPower": 30
 },
 "heartmail": {
  "category": "MAX"
 },
 "heartscale": {
  "category": "MAX",
  "flingPower": 30
 },
 "heatrock": {
  "category": "MAX",
  "effectParam": 3,
  "flingPower": 60,
  "hold": "extendsun"
 },
 "helixfossil": {
  "category": "MAX",
  "flingPower": 100
 },
 "hm01": {
  "category": "MAX"
 },
 "hm02": {
  "category": "MAX"
 },
 "hm03": {
  "category": "MAX"
 },
 "hm04": {
  "category": "MAX"
 },
 "hm05": {
  "category": "MAX"
 },
 "hm06": {
  "category": "MAX"
 },
 "hm07": {
  "category": "MAX"
 },
 "hm08": {
  "category": "MAX"
 },
 "hondewberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "ground"
 },
 "honey": {
  "category": "MAX",
  "flingPower": 30
 },
 "hpup": {
  "category": "MAX",
  "flingPower": 30
 },
 "hyperpotion": {
  "category": "RECOVER_HP",
  "hp": -56,
  "effectParam": 200,
  "flingPower": 30
 },
 "iapapaberry": {
  "category": "MAX",
  "effectParam": 8,
  "flingPower": 10,
  "naturalGiftType": "dark",
  "hold": "hprestoresour"
 },
 "iceheal": {
  "category": "RECOVER_STATUS",
  "cures": [
   "frz"
  ],
  "flingPower": 30
 },
 "icicleplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusice",
  "holdType": "ice"
 },
 "icyrock": {
  "category": "MAX",
  "effectParam": 3,
  "flingPower": 40,
  "hold": "extendhail"
 },
 "insectplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusbug",
  "holdType": "bug"
 },
 "iron": {
  "category": "MAX",
  "flingPower": 30
 },
 "ironball": {
  "category": "MAX",
  "flingPower": 130,
  "hold": "speeddowngrounded"
 },
 "ironplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceussteel",
  "holdType": "steel"
 },
 "jabocaberry": {
  "category": "MAX",
  "effectParam": 8,
  "flingPower": 10,
  "naturalGiftType": "dragon",
  "hold": "recoilphysical"
 },
 "journal": {
  "category": "MAX"
 },
 "kasibberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "ghost",
  "hold": "weakenseghost"
 },
 "kebiaberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "poison",
  "hold": "weakensepoison"
 },
 "kelpsyberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "fighting"
 },
 "kingsrock": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 30,
  "hold": "sometimesflinch"
 },
 "laggingtail": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "prioritydown"
 },
 "lansatberry": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 10,
  "naturalGiftType": "flying",
  "hold": "pinchcritrateup"
 },
 "lavacookie": {
  "category": "RECOVER_STATUS",
  "cures": [
   "slp",
   "psn",
   "brn",
   "frz",
   "par",
   "confusion"
  ],
  "flingPower": 30
 },
 "laxincense": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 10,
  "hold": "accreduce"
 },
 "leafstone": {
  "category": "MAX",
  "flingPower": 30
 },
 "leftovers": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 10,
  "hold": "hprestoregradual"
 },
 "lemonade": {
  "category": "RECOVER_HP",
  "hp": 80,
  "effectParam": 80,
  "flingPower": 30
 },
 "leppaberry": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 10,
  "naturalGiftType": "fighting",
  "hold": "pprestore"
 },
 "liechiberry": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 10,
  "naturalGiftType": "grass",
  "hold": "pinchatkup"
 },
 "lifeorb": {
  "category": "MAX",
  "effectParam": 30,
  "flingPower": 30,
  "hold": "hpdrainonatk"
 },
 "lightball": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "pikaspatkup"
 },
 "lightclay": {
  "category": "MAX",
  "effectParam": 3,
  "flingPower": 30,
  "hold": "extendscreens"
 },
 "lootsack": {
  "category": "MAX"
 },
 "luckincense": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 10,
  "hold": "moneyup"
 },
 "luckyegg": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "expup"
 },
 "luckypunch": {
  "category": "MAX",
  "flingPower": 40,
  "hold": "chanseycritrateup"
 },
 "lumberry": {
  "category": "RECOVER_STATUS",
  "cures": [
   "slp",
   "psn",
   "brn",
   "frz",
   "par",
   "confusion"
  ],
  "flingPower": 10,
  "naturalGiftType": "flying",
  "hold": "statusrestore"
 },
 "lunarwing": {
  "category": "MAX"
 },
 "lustrousorb": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 60,
  "hold": "palkiaboost"
 },
 "luxuryball": {
  "category": "POKEBALL"
 },
 "machobrace": {
  "category": "MAX",
  "flingPower": 60,
  "hold": "evsupspeeddown"
 },
 "magmastone": {
  "category": "MAX"
 },
 "magmarizer": {
  "category": "MAX",
  "flingPower": 80,
  "hold": "evolvemagmar"
 },
 "magnet": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 30,
  "hold": "strengthenelectric"
 },
 "magoberry": {
  "category": "MAX",
  "effectParam": 8,
  "flingPower": 10,
  "naturalGiftType": "ghost",
  "hold": "hprestoresweet"
 },
 "magostberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "rock"
 },
 "masterball": {
  "category": "POKEBALL"
 },
 "maxelixir": {
  "category": "MAX",
  "effectParam": 255,
  "flingPower": 30
 },
 "maxether": {
  "category": "MAX",
  "effectParam": 255,
  "flingPower": 30
 },
 "maxpotion": {
  "category": "RECOVER_HP",
  "hp": -1,
  "effectParam": 255,
  "flingPower": 30
 },
 "maxrepel": {
  "category": "MAX",
  "effectParam": 250,
  "flingPower": 30
 },
 "maxrevive": {
  "category": "RECOVER_HP",
  "hp": -1,
  "revive": true,
  "flingPower": 30
 },
 "meadowplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusgrass",
  "holdType": "grass"
 },
 "membercard": {
  "category": "MAX"
 },
 "mentalherb": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "healinfatuation"
 },
 "metalcoat": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 30,
  "hold": "strengthensteel"
 },
 "metalpowder": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "dittodefup"
 },
 "metronome": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 30,
  "hold": "boostrepeated"
 },
 "micleberry": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 10,
  "naturalGiftType": "rock",
  "hold": "pinchaccup"
 },
 "mindplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceuspsychic",
  "holdType": "psychic"
 },
 "miracleseed": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 30,
  "hold": "strengthengrass"
 },
 "moomoomilk": {
  "category": "RECOVER_HP",
  "hp": 100,
  "effectParam": 100,
  "flingPower": 30
 },
 "moonstone": {
  "category": "MAX",
  "flingPower": 30
 },
 "mosaicmail": {
  "category": "MAX"
 },
 "muscleband": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 10,
  "hold": "powerupphys"
 },
 "mysticwater": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 30,
  "hold": "strengthenwater"
 },
 "nanabberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "water"
 },
 "nestball": {
  "category": "POKEBALL"
 },
 "netball": {
  "category": "POKEBALL"
 },
 "nevermeltice": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 30,
  "hold": "strengthenice"
 },
 "nomelberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "dragon"
 },
 "none": {
  "category": "MAX",
  "naturalGiftType": "normal"
 },
 "nugget": {
  "category": "MAX",
  "flingPower": 30
 },
 "oaksletter": {
  "category": "MAX"
 },
 "occaberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "fire",
  "hold": "weakensefire"
 },
 "oddincense": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 10,
  "hold": "strengthenpsychic"
 },
 "oddkeystone": {
  "category": "MAX",
  "flingPower": 80
 },
 "oldamber": {
  "category": "MAX",
  "flingPower": 100
 },
 "oldcharm": {
  "category": "MAX"
 },
 "oldgateau": {
  "category": "RECOVER_STATUS",
  "cures": [
   "slp",
   "psn",
   "brn",
   "frz",
   "par",
   "confusion"
  ],
  "flingPower": 30
 },
 "oldrod": {
  "category": "MAX"
 },
 "oranberry": {
  "category": "RECOVER_HP",
  "hp": 10,
  "effectParam": 10,
  "flingPower": 10,
  "naturalGiftType": "poison",
  "hold": "hprestore"
 },
 "ovalstone": {
  "category": "MAX",
  "flingPower": 80
 },
 "palpad": {
  "category": "MAX"
 },
 "pamtreberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "steel"
 },
 "parcel": {
  "category": "MAX"
 },
 "parlyzheal": {
  "category": "RECOVER_STATUS",
  "cures": [
   "par"
  ],
  "flingPower": 30
 },
 "passhoberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "water",
  "hold": "weakensewater"
 },
 "payapaberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "psychic",
  "hold": "weakensepsychic"
 },
 "pearl": {
  "category": "MAX",
  "flingPower": 30
 },
 "pechaberry": {
  "category": "RECOVER_STATUS",
  "cures": [
   "psn"
  ],
  "flingPower": 10,
  "naturalGiftType": "electric",
  "hold": "psnrestore"
 },
 "persimberry": {
  "category": "RECOVER_STATUS",
  "cures": [
   "confusion"
  ],
  "flingPower": 10,
  "naturalGiftType": "ground",
  "hold": "confuserestore"
 },
 "petayaberry": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 10,
  "naturalGiftType": "poison",
  "hold": "pinchspatkup"
 },
 "pinapberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "grass"
 },
 "pinkscarf": {
  "category": "MAX",
  "flingPower": 10
 },
 "poffincase": {
  "category": "MAX"
 },
 "pointcard": {
  "category": "MAX"
 },
 "poisonbarb": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 70,
  "hold": "strengthenpoison"
 },
 "pokeball": {
  "category": "POKEBALL"
 },
 "pokedoll": {
  "category": "MAX",
  "flingPower": 30
 },
 "pokeradar": {
  "category": "MAX"
 },
 "pomegberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "ice"
 },
 "potion": {
  "category": "RECOVER_HP",
  "hp": 20,
  "effectParam": 20,
  "flingPower": 30
 },
 "poweranklet": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 70,
  "hold": "lvlupspeedevup"
 },
 "powerband": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 70,
  "hold": "lvlupspdefevup"
 },
 "powerbelt": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 70,
  "hold": "lvlupdefevup"
 },
 "powerbracer": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 70,
  "hold": "lvlupatkevup"
 },
 "powerherb": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "chargeskip"
 },
 "powerlens": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 70,
  "hold": "lvlupspatkevup"
 },
 "powerweight": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 70,
  "hold": "lvluphpevup"
 },
 "ppmax": {
  "category": "MAX",
  "flingPower": 30
 },
 "ppup": {
  "category": "MAX",
  "flingPower": 30
 },
 "premierball": {
  "category": "POKEBALL"
 },
 "protector": {
  "category": "MAX",
  "flingPower": 80,
  "hold": "evolverhydon"
 },
 "protein": {
  "category": "MAX",
  "flingPower": 30
 },
 "pureincense": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "encountersdown"
 },
 "qualotberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "poison"
 },
 "quickball": {
  "category": "POKEBALL"
 },
 "quickclaw": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 80,
  "hold": "sometimespriority"
 },
 "quickpowder": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "dittospeedup"
 },
 "rabutaberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "ghost"
 },
 "rarebone": {
  "category": "MAX",
  "flingPower": 100
 },
 "rarecandy": {
  "category": "MAX",
  "revive": true,
  "flingPower": 30
 },
 "rawstberry": {
  "category": "RECOVER_STATUS",
  "cures": [
   "brn"
  ],
  "flingPower": 10,
  "naturalGiftType": "grass",
  "hold": "brnrestore"
 },
 "razorclaw": {
  "category": "MAX",
  "flingPower": 80,
  "hold": "critrateup"
 },
 "razorfang": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 30,
  "hold": "sometimesflinch"
 },
 "razzberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "steel"
 },
 "reapercloth": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "evolvedusclops"
 },
 "redchain": {
  "category": "MAX"
 },
 "redflute": {
  "category": "MAX",
  "flingPower": 30
 },
 "redscarf": {
  "category": "MAX",
  "flingPower": 10
 },
 "redshard": {
  "category": "MAX",
  "flingPower": 30
 },
 "repeatball": {
  "category": "POKEBALL"
 },
 "repel": {
  "category": "MAX",
  "effectParam": 100,
  "flingPower": 30
 },
 "revivalherb": {
  "category": "RECOVER_HP",
  "hp": -1,
  "revive": true,
  "flingPower": 30
 },
 "revive": {
  "category": "RECOVER_HP",
  "hp": -2,
  "revive": true,
  "flingPower": 30
 },
 "rindoberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "grass",
  "hold": "weakensegrass"
 },
 "rockincense": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 10,
  "hold": "strengthenrock"
 },
 "rootfossil": {
  "category": "MAX",
  "flingPower": 100
 },
 "roseincense": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 10,
  "hold": "strengthengrass"
 },
 "rowapberry": {
  "category": "MAX",
  "effectParam": 8,
  "flingPower": 10,
  "naturalGiftType": "dark",
  "hold": "recoilspecial"
 },
 "rulebook": {
  "category": "MAX"
 },
 "ssticket": {
  "category": "MAX"
 },
 "sacredash": {
  "category": "RECOVER_HP",
  "hp": -1,
  "revive": true,
  "flingPower": 30
 },
 "safariball": {
  "category": "POKEBALL"
 },
 "salacberry": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 10,
  "naturalGiftType": "fighting",
  "hold": "pinchspeedup"
 },
 "scopelens": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "critrateup"
 },
 "seaincense": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 10,
  "hold": "strengthenwater"
 },
 "sealbag": {
  "category": "MAX"
 },
 "sealcase": {
  "category": "MAX"
 },
 "secretkey": {
  "category": "MAX"
 },
 "secretpotion": {
  "category": "MAX"
 },
 "sharpbeak": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 50,
  "hold": "strengthenflying"
 },
 "shedshell": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "switch"
 },
 "shellbell": {
  "category": "MAX",
  "effectParam": 8,
  "flingPower": 30,
  "hold": "hprestoreondmg"
 },
 "shinystone": {
  "category": "MAX",
  "flingPower": 80
 },
 "shoalsalt": {
  "category": "MAX",
  "flingPower": 30
 },
 "shoalshell": {
  "category": "MAX",
  "flingPower": 30
 },
 "shucaberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "ground",
  "hold": "weakenseground"
 },
 "silkscarf": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 10,
  "hold": "strengthennormal"
 },
 "silverpowder": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 10,
  "hold": "strengthenbug"
 },
 "sitrusberry": {
  "category": "RECOVER_HP",
  "hp": -3,
  "effectParam": 25,
  "flingPower": 10,
  "naturalGiftType": "psychic",
  "hold": "hppctrestore"
 },
 "skullfossil": {
  "category": "MAX",
  "flingPower": 100
 },
 "skyplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusflying",
  "holdType": "flying"
 },
 "smokeball": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "flee"
 },
 "smoothrock": {
  "category": "MAX",
  "effectParam": 3,
  "flingPower": 10,
  "hold": "extendsandstorm"
 },
 "snowmail": {
  "category": "MAX"
 },
 "sodapop": {
  "category": "RECOVER_HP",
  "hp": 60,
  "effectParam": 60,
  "flingPower": 30
 },
 "softsand": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 10,
  "hold": "strengthenground"
 },
 "soothebell": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "friendshipup"
 },
 "souldew": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "latispecial"
 },
 "spacemail": {
  "category": "MAX"
 },
 "spelltag": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 30,
  "hold": "strengthenghost"
 },
 "spelonberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "dark"
 },
 "splashplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceuswater",
  "holdType": "water"
 },
 "spookyplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusghost",
  "holdType": "ghost"
 },
 "sprayduck": {
  "category": "MAX"
 },
 "stablemulch": {
  "category": "MAX",
  "flingPower": 30
 },
 "starpiece": {
  "category": "MAX",
  "flingPower": 30
 },
 "stardust": {
  "category": "MAX",
  "flingPower": 30
 },
 "starfberry": {
  "category": "MAX",
  "effectParam": 4,
  "flingPower": 10,
  "naturalGiftType": "psychic",
  "hold": "pinchrandomup"
 },
 "steelmail": {
  "category": "MAX"
 },
 "stick": {
  "category": "MAX",
  "flingPower": 60,
  "hold": "farfetchdcritrateup"
 },
 "stickybarb": {
  "category": "MAX",
  "effectParam": 8,
  "flingPower": 80,
  "hold": "dmgusercontactxfr"
 },
 "stoneplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceusrock",
  "holdType": "rock"
 },
 "storagekey": {
  "category": "MAX"
 },
 "suitekey": {
  "category": "MAX"
 },
 "sunstone": {
  "category": "MAX",
  "flingPower": 30
 },
 "superpotion": {
  "category": "RECOVER_HP",
  "hp": 50,
  "effectParam": 50,
  "flingPower": 30
 },
 "superrepel": {
  "category": "MAX",
  "effectParam": 200,
  "flingPower": 30
 },
 "superrod": {
  "category": "MAX"
 },
 "tamatoberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "psychic"
 },
 "tangaberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "bug",
  "hold": "weakensebug"
 },
 "thickclub": {
  "category": "MAX",
  "flingPower": 90,
  "hold": "cuboneatkup"
 },
 "thunderstone": {
  "category": "MAX",
  "flingPower": 30
 },
 "timerball": {
  "category": "POKEBALL"
 },
 "tinymushroom": {
  "category": "MAX",
  "flingPower": 30
 },
 "tm01": {
  "category": "MAX"
 },
 "tm02": {
  "category": "MAX"
 },
 "tm03": {
  "category": "MAX"
 },
 "tm04": {
  "category": "MAX"
 },
 "tm05": {
  "category": "MAX"
 },
 "tm06": {
  "category": "MAX"
 },
 "tm07": {
  "category": "MAX"
 },
 "tm08": {
  "category": "MAX"
 },
 "tm09": {
  "category": "MAX"
 },
 "tm10": {
  "category": "MAX"
 },
 "tm11": {
  "category": "MAX"
 },
 "tm12": {
  "category": "MAX"
 },
 "tm13": {
  "category": "MAX"
 },
 "tm14": {
  "category": "MAX"
 },
 "tm15": {
  "category": "MAX"
 },
 "tm16": {
  "category": "MAX"
 },
 "tm17": {
  "category": "MAX"
 },
 "tm18": {
  "category": "MAX"
 },
 "tm19": {
  "category": "MAX"
 },
 "tm20": {
  "category": "MAX"
 },
 "tm21": {
  "category": "MAX"
 },
 "tm22": {
  "category": "MAX"
 },
 "tm23": {
  "category": "MAX"
 },
 "tm24": {
  "category": "MAX"
 },
 "tm25": {
  "category": "MAX"
 },
 "tm26": {
  "category": "MAX"
 },
 "tm27": {
  "category": "MAX"
 },
 "tm28": {
  "category": "MAX"
 },
 "tm29": {
  "category": "MAX"
 },
 "tm30": {
  "category": "MAX"
 },
 "tm31": {
  "category": "MAX"
 },
 "tm32": {
  "category": "MAX"
 },
 "tm33": {
  "category": "MAX"
 },
 "tm34": {
  "category": "MAX"
 },
 "tm35": {
  "category": "MAX"
 },
 "tm36": {
  "category": "MAX"
 },
 "tm37": {
  "category": "MAX"
 },
 "tm38": {
  "category": "MAX"
 },
 "tm39": {
  "category": "MAX"
 },
 "tm40": {
  "category": "MAX"
 },
 "tm41": {
  "category": "MAX"
 },
 "tm42": {
  "category": "MAX"
 },
 "tm43": {
  "category": "MAX"
 },
 "tm44": {
  "category": "MAX"
 },
 "tm45": {
  "category": "MAX"
 },
 "tm46": {
  "category": "MAX"
 },
 "tm47": {
  "category": "MAX"
 },
 "tm48": {
  "category": "MAX"
 },
 "tm49": {
  "category": "MAX"
 },
 "tm50": {
  "category": "MAX"
 },
 "tm51": {
  "category": "MAX"
 },
 "tm52": {
  "category": "MAX"
 },
 "tm53": {
  "category": "MAX"
 },
 "tm54": {
  "category": "MAX"
 },
 "tm55": {
  "category": "MAX"
 },
 "tm56": {
  "category": "MAX"
 },
 "tm57": {
  "category": "MAX"
 },
 "tm58": {
  "category": "MAX"
 },
 "tm59": {
  "category": "MAX"
 },
 "tm60": {
  "category": "MAX"
 },
 "tm61": {
  "category": "MAX"
 },
 "tm62": {
  "category": "MAX"
 },
 "tm63": {
  "category": "MAX"
 },
 "tm64": {
  "category": "MAX"
 },
 "tm65": {
  "category": "MAX"
 },
 "tm66": {
  "category": "MAX"
 },
 "tm67": {
  "category": "MAX"
 },
 "tm68": {
  "category": "MAX"
 },
 "tm69": {
  "category": "MAX"
 },
 "tm70": {
  "category": "MAX"
 },
 "tm71": {
  "category": "MAX"
 },
 "tm72": {
  "category": "MAX"
 },
 "tm73": {
  "category": "MAX"
 },
 "tm74": {
  "category": "MAX"
 },
 "tm75": {
  "category": "MAX"
 },
 "tm76": {
  "category": "MAX"
 },
 "tm77": {
  "category": "MAX"
 },
 "tm78": {
  "category": "MAX"
 },
 "tm79": {
  "category": "MAX"
 },
 "tm80": {
  "category": "MAX"
 },
 "tm81": {
  "category": "MAX"
 },
 "tm82": {
  "category": "MAX"
 },
 "tm83": {
  "category": "MAX"
 },
 "tm84": {
  "category": "MAX"
 },
 "tm85": {
  "category": "MAX"
 },
 "tm86": {
  "category": "MAX"
 },
 "tm87": {
  "category": "MAX"
 },
 "tm88": {
  "category": "MAX"
 },
 "tm89": {
  "category": "MAX"
 },
 "tm90": {
  "category": "MAX"
 },
 "tm91": {
  "category": "MAX"
 },
 "tm92": {
  "category": "MAX"
 },
 "townmap": {
  "category": "MAX"
 },
 "toxicorb": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "psnuser"
 },
 "toxicplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceuspoison",
  "holdType": "poison"
 },
 "tunnelmail": {
  "category": "MAX"
 },
 "twistedspoon": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 30,
  "hold": "strengthenpsychic"
 },
 "ultraball": {
  "category": "POKEBALL"
 },
 "upgrade": {
  "category": "MAX",
  "flingPower": 30,
  "hold": "evolveporygon"
 },
 "vsrecorder": {
  "category": "MAX"
 },
 "vsseeker": {
  "category": "MAX"
 },
 "wacanberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "electric",
  "hold": "weakenseelectric"
 },
 "waterstone": {
  "category": "MAX",
  "flingPower": 30
 },
 "watmelberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "fire"
 },
 "waveincense": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 10,
  "hold": "strengthenwater"
 },
 "wepearberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "electric"
 },
 "whiteflute": {
  "category": "MAX",
  "effectParam": 150,
  "flingPower": 30
 },
 "whiteherb": {
  "category": "MAX",
  "flingPower": 10,
  "hold": "statdownrestore"
 },
 "widelens": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 10,
  "hold": "accuracyup"
 },
 "wikiberry": {
  "category": "MAX",
  "effectParam": 8,
  "flingPower": 10,
  "naturalGiftType": "rock",
  "hold": "hprestoredry"
 },
 "wiseglasses": {
  "category": "MAX",
  "effectParam": 10,
  "flingPower": 10,
  "hold": "powerupspec"
 },
 "workskey": {
  "category": "MAX"
 },
 "xaccuracy": {
  "category": "STAT_BOOSTER",
  "stages": {
   "acc": 1
  },
  "flingPower": 30
 },
 "xattack": {
  "category": "STAT_BOOSTER",
  "stages": {
   "atk": 1
  },
  "flingPower": 30
 },
 "xdefense": {
  "category": "STAT_BOOSTER",
  "stages": {
   "def": 1
  },
  "flingPower": 30
 },
 "xspdef": {
  "category": "STAT_BOOSTER",
  "stages": {
   "spdef": 1
  },
  "flingPower": 30
 },
 "xspecial": {
  "category": "STAT_BOOSTER",
  "stages": {
   "spatk": 1
  },
  "flingPower": 30
 },
 "xspeed": {
  "category": "STAT_BOOSTER",
  "stages": {
   "speed": 1
  },
  "flingPower": 30
 },
 "yacheberry": {
  "category": "MAX",
  "flingPower": 10,
  "naturalGiftType": "ice",
  "hold": "weakenseice"
 },
 "yellowflute": {
  "category": "RECOVER_STATUS",
  "cures": [
   "confusion"
  ],
  "flingPower": 30
 },
 "yellowscarf": {
  "category": "MAX",
  "flingPower": 10
 },
 "yellowshard": {
  "category": "MAX",
  "flingPower": 30
 },
 "zapplate": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 90,
  "hold": "arceuselectric",
  "holdType": "electric"
 },
 "zinc": {
  "category": "MAX",
  "flingPower": 30
 },
 "zoomlens": {
  "category": "MAX",
  "effectParam": 20,
  "flingPower": 10,
  "hold": "accuracyupslower"
 }
};
